name: Sincronizar repositórios

on:
  push:
    branches:
      - main
  # Você pode adicionar mais gatilhos, como agendados
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do repositório de origem (workflow)
      - name: Checkout do repositório de origem
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ================================
      # Opção 1: Push direto para o cliente
      # ================================
      - name: Push direto para o cliente (opção simples)
        env:
          CLIENT_REPO_TOKEN: ${{ secrets.CLIENT_REPO_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Adicionar remote do cliente
          git remote add client https://x-access-token:$CLIENT_REPO_TOKEN@github.com/OctusLab/POC-upstream.git

          # Push direto da branch main
          git push client main --force

      # ================================
      # Opção 2: Clone do cliente + merge manual
      # ================================
      - name: Clone cliente e merge manual (opção alternativa)
        env:
          CLIENT_REPO_TOKEN: ${{ secrets.CLIENT_REPO_TOKEN }}
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          ORG_NAME: SeuOrgOuUsuario  # Substitua pelo seu org/usuário
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Clonar o repositório do cliente
          git clone https://x-access-token:$CLIENT_REPO_TOKEN@github.com/OctusLab/POC-upstream.git
          cd POC-upstream

          # Adicionar remote do repositório original
          git remote add origin_repo https://x-access-token:$CLIENT_REPO_TOKEN@github.com/${ORG_NAME}/${ORIGINAL_REPO_NAME}.git

          # Buscar commits da branch main do repositório original
          git fetch origin_repo main

          # Mesclar alterações
          git merge origin_repo/main

          # Push para o cliente
          git push origin main --force
