name: Sync to Client Fork

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to client fork
        run: |
          git remote add client https://x-access-token:${{ secrets.CLIENT_REPO_TOKEN }}@github.com/OctusLab/POC-upstream.git
          git push --force client main
